In [79]:
import torch

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0],
 [1,0,0], [1,0,0] ])

In [80]:
## W,b 초기화
## Optimizer 생성

W = torch.zeros(4, 3, requires_grad=True)
b = torch.zeros(1, 3, requires_grad=True)
optimizer = torch.optim.Adam([W,b], lr=0.1)

for epoch in range(3001):
  hypothesis = torch.softmax(torch.mm(x_train, W)+b, dim=1)
  cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim=1))
  hypothesis = (torch.mm(x_train, W)+b).softmax(dim=1)
  cost = -(y_train * torch.log(hypothesis)).sum(dim=1).mean()

  optimizer.zero_grad()
  cost.backward()
  optimizer.step()


  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105262
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [81]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.softmax(torch.mm(x_test, W)+b, dim=1)

print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 5.5165e-19, 7.0151e-38],
        [1.4800e-02, 7.4294e-01, 2.4226e-01],
        [1.2256e-33, 9.0835e-12, 1.0000e+00]])
tensor([0, 1, 2])


조금 더 깔끔하게 Softmax

In [9]:
import torch

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([ 2, 2, 2, 1, 1, 1, 0, 0 ])

In [10]:
import torch.nn.functional as F

W = torch.zeros(4, 3, requires_grad=True)
b = torch.zeros(1, 3, requires_grad=True)
optimizer = torch.optim.Adam([W,b], lr=0.1)

for epoch in range(3001):
 z = torch.mm(x_train, W)+b
 cost = F.cross_entropy(z, y_train)
 
 optimizer.zero_grad()
 cost.backward()
 optimizer.step()

 if epoch % 300 == 0:
  print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 1.098612
epoch: 300, cost: 0.105263
epoch: 600, cost: 0.042634
epoch: 900, cost: 0.023111
epoch: 1200, cost: 0.014479
epoch: 1500, cost: 0.009879
epoch: 1800, cost: 0.007124
epoch: 2100, cost: 0.005338
epoch: 2400, cost: 0.004113
epoch: 2700, cost: 0.003236
epoch: 3000, cost: 0.002588


In [11]:
W.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = torch.mm(x_test, W)+b

print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[ 39.3535,  -2.6879, -46.1967],
        [ -5.5873,  -1.6713,  -2.7919],
        [-44.3165,   6.0408,  31.4654]])
tensor([0, 1, 2])


In [1]:
import torch

x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.LongTensor([ 2, 2, 2, 1, 1, 1, 0, 0 ])

In [3]:
import torch.nn.functional as F
import torch.nn as nn

model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(),lr=1)

for epoch in range(3001):
  z = model(x_train)
  cost = F.cross_entropy(z, y_train)


  optimizer.zero_grad()
  cost.backward()
  optimizer.step()

  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 2.127651
epoch: 300, cost: 0.032930
epoch: 600, cost: 0.013113
epoch: 900, cost: 0.007087
epoch: 1200, cost: 0.004445
epoch: 1500, cost: 0.003039
epoch: 1800, cost: 0.002196
epoch: 2100, cost: 0.001648
epoch: 2400, cost: 0.001272
epoch: 2700, cost: 0.001002
epoch: 3000, cost: 0.000802


In [7]:
x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
test_all = model(x_test)

print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[ 68.7222,  14.6927, -39.6412],
        [ -1.8296,  10.3546,   7.4684],
        [-50.0765,  15.4791,  46.8552]], grad_fn=<AddmmBackward>)
tensor([0, 1, 2])


Softmax Regression in Sklearn

In [88]:
import numpy as np
from sklearn.linear_model import LogisticRegression
x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])

# y에 0, 1, 2 등 둘 이상의 class가 존재 => softmax regression
y_train = np.array([ 2, 2, 2, 1, 1, 1, 0, 0 ])

logistic = LogisticRegression() # 모델 생성
logistic.fit(x_train, y_train) # 학습
pred = logistic.predict([[1,11,10,9], [1,3,4,3], [1,1,0,1]]) # test case (값 예측)
print(pred) # 출력

[0 2 2]
